export const UPDATE_POSTS_LIST = 'UPDATE_POSTS_LIST';
export const CHANGE_POSTS = 'CHANGE_POSTS';

export const SHOW_ARTICLE_MANAGEMENT_WINDOW = 'SHOW_ARTICLE_MANAGEMENT_WINDOW';
export const HIDE_ARTICLE_MANAGEMENT_WINDOW = 'HIDE_ARTICLE_MANAGEMENT_WINDOW';
