export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';

export const GET_POST = 'GET_POST';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_FULFILLED = 'UPDATE_POST_FULFILLED';
export const UPDATE_POST_REJECTED = 'UPDATE_POST_REJECTED';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED';
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED';

export const SHOW_ARTICLE_MANAGEMENT_WINDOW = 'SHOW_ARTICLE_MANAGEMENT_WINDOW';
export const HIDE_ARTICLE_MANAGEMENT_WINDOW = 'HIDE_ARTICLE_MANAGEMENT_WINDOW';
